name: Label Pull Requests
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/labeler
    - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7
      with:
        repo-token: "${{ secrets.WALL_BREW_BOT_PAT }}"
