name: Linter
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  spell-check:
    name: Spellchecker
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.head_ref }}

      # https://github.com/reviewdog/action-misspell
      - name: misspell
        uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 # v1
        with:
          github_token: ${{ secrets.WALL_BREW_BOT_PAT }}
          locale: "US"
          reporter: github-pr-review
          filter_mode: file

  markdownlint:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.head_ref }}

      # https://github.com/reviewdog/action-markdownlint
      - name: Lint Markdown
        uses: reviewdog/action-markdownlint@844fd04b127b0d78328653f182d32988ad41d3d7 # v0.27.0
        with:
          github_token: ${{ secrets.WALL_BREW_BOT_PAT }}
          reporter: github-pr-review
          filter_mode: file
