name: Linter
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  spell-check:
    name: Spellchecker
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          ref: ${{ github.head_ref }}

      # https://github.com/reviewdog/action-misspell
      - name: misspell
        uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 # v1
        with:
          github_token: ${{ secrets.WALL_BREW_BOT_PAT }}
          locale: "US"
          reporter: github-pr-review
          filter_mode: file

  markdownlint:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          ref: ${{ github.head_ref }}

      # https://github.com/reviewdog/action-markdownlint
      - name: Lint Markdown
        uses: reviewdog/action-markdownlint@6f0e0e8703a9e840ffefa37a2775832c51c1c640 # v0.28.0
        with:
          github_token: ${{ secrets.WALL_BREW_BOT_PAT }}
          reporter: github-pr-review
          filter_mode: file
